spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/instagram_clone_db?createDatabaseIfNotExist=true
    username: postgres
    password: Str0ngPa$$w0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Use validate since we're using Flyway for migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    clean-disabled: false